<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb55602026dbfbe4ef30fe356d0bb1e8d
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb55602026dbfbe4ef30fe356d0bb1e8d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb55602026dbfbe4ef30fe356d0bb1e8d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb55602026dbfbe4ef30fe356d0bb1e8d::$classMap;

        }, null, ClassLoader::class);
    }
}
